# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-06 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('na_laalii_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
