# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-02 19:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('na_laalii_app', '0002_auto_20180806_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtrlinfo',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='mtrlinfo',
            name='mapp_address',
            field=models.ImageField(upload_to='map_address'),
        ),
    ]
