# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-02 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('na_laalii_app', '0003_auto_20180902_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtrlinfo',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
