# Generated by Django 2.1 on 2018-10-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('na_laalii_app', '0005_auto_20181005_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='email',
        ),
    ]
