# Generated by Django 2.1 on 2018-10-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('na_laalii_app', '0006_remove_dealer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='email',
            field=models.EmailField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
