# Generated by Django 2.1 on 2019-07-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('na_laalii_app', '0008_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('bg1', models.ImageField(upload_to='')),
                ('bg2', models.ImageField(upload_to='')),
            ],
        ),
    ]
