# Generated by Django 2.1 on 2019-07-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('na_laalii_app', '0010_auto_20190701_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='keyword',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
