# Generated by Django 2.2.9 on 2020-01-16 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('na_laalii_app', '0011_dealer_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtrlinfo',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='na_laalii_app.DEALER'),
        ),
        migrations.AlterField(
            model_name='mtrlinfo',
            name='mapp_address',
            field=models.ImageField(blank=True, upload_to='map_address'),
        ),
    ]
